### ISSUE TITLE
Check if Docker is already installed

### ISSUE THREAD

**Issue by deimosfr** [lesmyrmidons/ansible-role-docker#1]
Hi,

Nice Ansible role :-). However, you should check if Docker is installed instead of launching this part each time:

```
- name: Install docker for debian wheesy
shell: curl -sSL https://get.docker.com/ | sh
when: ansible_distribution_release == 'wheezy'
```

Thanks

**Comment by lesmyrmidons** [comment]
Thank you for your return.
Adding the test and also dependent curl package
